version: '3'

services:
  weather-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    volumes:
      - ./weather.db:/app/weather.db